- hosts: java
  tasks:
  # Create Groups

   - name: "Add group"
     group:
       name: "{{oracle_group}}"
       gid: 1010
       state: present

# Create Users

   - name: "Add user"
     user:
       name: "{{oracle_user}}"
       uid: 500
       groups: oinstall
       password: "{{oracle_os_password}}"
       state: present
       shell: /bin/bash       # Defaults to /bin/bash
       system: no             # Defaults to no
       createhome: yes        # Defaults to yes
       home: /home/oracle  # Defaults to /home/<username>

  

