- name: "Creating multiple by checking folders"
  hosts: all
  
- name: Adding user oracle
  hosts: all  
  user: name=oracle
        shell=/bin/bash
        password=oracle        
        append=yes