- name: "Creating User and Group"
  hosts: all
  tasks:
  - block:

    - group:
      name: oinstall
      gid: 1000
      state: present
    
    - user:
      name: oracle
      uid: 500
      group: oinstall
      append: yes
      shell: /bin/bash
   

    